// AUTO-GENERATED by scripts/obsidian-generator.mjs — do not edit.
// Generated: 2026-09-07T11:35:24.084Z
// Vault   : /home/void/Entertainment/Obsidian/Void

import type { ObsidianCategory } from '@/dashboard/lib/obsidian'

export const obsidianCategories: ObsidianCategory[] = [
  {
    "id": "cognizant",
    "label": "Cognizant",
    "emoji": "💼",
    "color": "#34d399",
    "description": "Employment snapshots and Jira ticket tracking.",
    "folder": "Cognizant",
    "noteCount": 120,
    "fileCount": 120,
    "subfolderCount": 1,
    "dataUrl": "obsidian-data/cognizant.json",
    "generatedAt": "2026-09-07T11:35:24.084Z"
  },
  {
    "id": "meldora",
    "label": "Meldora Novel",
    "emoji": "📖",
    "color": "#a78bfa",
    "description": "Fantasy novel project — manuscript, characters, worldbuilding, power systems and plot.",
    "folder": "Meldora_Novel_Vault",
    "noteCount": 47,
    "fileCount": 47,
    "subfolderCount": 13,
    "dataUrl": "obsidian-data/meldora.json",
    "generatedAt": "2026-09-07T11:35:24.084Z"
  },
  {
    "id": "project-ideas",
    "label": "Project Ideas",
    "emoji": "💡",
    "color": "#fbbf24",
    "description": "Future project planning and ideas.",
    "folder": "PROJECT IDEAS",
    "noteCount": 2,
    "fileCount": 2,
    "subfolderCount": 0,
    "dataUrl": "obsidian-data/project-ideas.json",
    "generatedAt": "2026-09-07T11:35:24.084Z"
  }
]

export const obsidianGeneratedAt = "2026-09-07T11:35:24.084Z"
export const obsidianTotalNotes = 169
